config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations'
  }

  resources :users, only: %i[show edit update index] do
    member do
      get 'followers'
      get 'followings'
    end
    resource :relationships, only: %i[create destroy]
    resource :rooms, only: %i[show] do
      resources :chats, only: %i[create]
    end
  end

  resources :books do
    resource :favorites, only: %i[create destroy]
    resources :book_comments, only: %i[create]
  end

  resources :book_comments, only: %i[destroy]
  resources :chats, only: %i[destroy]

  root 'home#top'
  get 'home/about'
  get 'search' => 'searchs#search', as: 'search'
  patch 'map_display' => 'users#map_display', as: 'map_display'
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/controllers/favorites_controller.rb
# frozen_string_literal: true

class FavoritesController < ApplicationController
  before_action :authenticate_user!

  # POST /books/:book_id/favorites
  def create
    return unless Favorite.find_by(book_id: params[:book_id], user_id: current_user.id).nil?

    @favorite = current_user.favorites.new(book_id: params[:book_id])
    @favorite.save
  end

  # DELETE /books/:book_id/favorites/
  def destroy
    return if Favorite.find_by(book_id: params[:book_id], user_id: current_user.id).nil?

    @favorite = Favorite.find_by(user_id: current_user, book_id: params[:book_id])
    @favorite.destroy
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_book.html.slim
- if book.favorited_by?(user)
  = link_to "★ #{book.favorites.count}", book_favorites_path(book), method: :delete, remote: true
- else
  = link_to "☆ #{book.favorites.count}", book_favorites_path(book), method: :post, remote: true

app/views/favorites/create.js.erb
$('.books_favorite__table--<%= @favorite.book_id %>').html(
  "<%= j(render partial: 'book', locals: {book: @favorite.book, user: @favorite.user}) %>"
)

app/views/favorites/destroy.js.erb
$('.books_favorite__table--<%= @favorite.book_id %>').html(
  "<%= j(render partial: 'book', locals: {book: @favorite.book, user: @favorite.user}) %>"
)