config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations'
  }

  resources :users, only: %i[show edit update index] do
    member do
      get 'followers'
      get 'followings'
    end
    resource :relationships, only: %i[create destroy]
    resource :rooms, only: %i[show] do
      resources :chats, only: %i[create]
    end
  end

  resources :books do
    resource :favorites, only: %i[create destroy]
    resources :book_comments, only: %i[create]
  end

  resources :book_comments, only: %i[destroy]
  resources :chats, only: %i[destroy]

  root 'home#top'
  get 'home/about'
  get 'search' => 'searchs#search', as: 'search'
  patch 'map_display' => 'users#map_display', as: 'map_display'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  include JpPrefecture

  jp_prefecture :prefectures

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable

  attachment :profile_image, destroy: false

  has_many :books
  has_many :favorites
  has_many :book_comments
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followee_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, foreign_key: 'follower_id', dependent: :destroy
  has_many :followings, through: :relationships, source: :followee
  has_many :user_rooms, dependent: :delete_all
  has_many :chats, dependent: :delete_all

  validates :name, presence: true, length: { maximum: 10, minimum: 2 }
  validates :introduction, length: { maximum: 50 }
  validates :postal_code, presence: true
  validates :prefectures, presence: true
  validates :city, presence: true
  validates :street, presence: true

  # enum prefectures: {
  #   hokkaido: 1,
  #   aomori: 2, iwate: 3, miyagi: 4, akita: 5, yamagata: 6, fukushima: 7,
  #   ibaraki: 8, tochigi: 9, gunma: 10, saitama: 11,
  #   chiba: 12, tokyo: 13, kanagawa: 14,
  #   niigata: 15, toyama: 16, ishikawa: 17, fukui: 18,
  #   yamanashi: 19, nagano: 20, gifu: 21, shizuoka: 22,
  #   aichi: 23, mie: 24, shiga: 25, kyoto: 26,
  #   osaka: 27, hyogo: 28, nara: 29, wakayama: 30,
  #   tottori: 31, shimane: 32, okayama: 33, hiroshima: 34,
  #   yamaguchi: 35, tokushima: 36, kagawa: 37, ehime: 38,
  #   kochi: 39, fukuoka: 40, saga: 41, nagasaki: 42,
  #   kumamoto: 43, oita: 44, miyazaki: 45, kagoshima: 46,
  #   okinawa: 47
  # }

  def following?(another_user)
    followings.include?(another_user)
  end

  def follow(another_user)
    return if self == another_user

    relationships.find_or_create_by(followee_id: another_user.id)
  end

  def unfollow(another_user)
    return if self == another_user

    relationship = relationships.find_by(followee_id: another_user.id)
    relationship&.destroy
  end

  def self.search(content, method)
    case method
    when 'perfect'
      where(name: content)
    when 'forward'
      where('name LIKE ?', "#{content}%")
    when 'backward'
      where('name LIKE ?', "%#{content}")
    when 'partial'
      where('name LIKE ?', "%#{content}%")
    end
  end

  def latlng
    return unless is_display_map

    begin
      Geocoder.search(prefectures + city).first.coordinates
    rescue
      update(is_display_map: false)
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :screen_user, only: %i[edit update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def followings
    @book = Book.new
    @user = User.find(params[:id])
  end

  def followers
    @book = Book.new
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def map_display
    if current_user.is_display_map
      current_user.update(is_display_map: false)
    else
      current_user.update(is_display_map: true)
      current_user.latlng
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :email, :postal_code, :prefectures, :city, :street, :building)
  end

  def screen_user
    return if params[:id].to_i == current_user.id

    redirect_to current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_btn.html.slim
- unless current_user == user
  - if current_user.following?(user)
    = link_to "フォロー中", user_relationships_path(user), method: :delete, class:"btn btn-success"
  - else
    = link_to "フォローする", user_relationships_path(user), method: :post, class:"btn btn-light"

app/views/users/_index.html.slim
.row
  h2 Users
  table.table.table-hover.table-inverse.users_index__table.col-md-12
    thead
      tr
        th image
        th name
        th[colspan="4"]
    tbody
      - users.each do |user|
        tr
          td = attachment_image_tag(user, :profile_image, size: "50x50", fallback: "no-image-icon.jpg")
          td = user.name
          td = "フォロー数：#{user.followings.count}"
          td = "フォロワー数：#{user.followers.count}"
          td == render 'users/follow_btn', user: user
          td = link_to 'Show', user, class: "btn btn-info"

app/views/users/_info.html.slim
.row.mb-5

  h2 User info
  .col-md-12
    .row
      table.table.col-md-12
        tr
          td = attachment_image_tag(user, :profile_image, size: '100x100', fallback: 'no_image.jpg')
          td
            - if current_user == user
              - if current_user.is_display_map
                = link_to 'MAP 表示中', map_display_path, method: :patch, class: 'btn btn-primary'
              - else
                = link_to 'MAP 非表示', map_display_path, method: :patch, class: 'btn btn-light'
            - else
              == render 'users/follow_btn', user: user
        tr
          th name
          td = user.name
        tr
          th ntroduction
          td = user.introduction
        tr
          th フォロー
          td = link_to "#{user.followings.count}人", followings_user_path(user)
        tr
          th フォロワー
          td = link_to "#{user.followers.count}人", followers_user_path(user)

    .row
      - if user == current_user
        = link_to 'Edit', edit_user_path(user), class: "col-md-12 btn btn-primary"
      - else
        = link_to 'Chat', user_rooms_path(user), method: :get, class: "col-md-12 btn btn-primary", data: {"turbolinks" => false}

app/views/users/_map.html.erb
<% if user_signed_in? %>
<% if (request.fullpath[0, 7] != "/users/" || request.fullpath == "/users/#{current_user.id}") && current_user.is_display_map %>
    <div>
      <h2>My MAP（<%= current_user.prefectures + current_user.city %>）<h2>
      <div id="map"></div>
    </div>
  <script>
    let myLatLng, map, marker;
    function initMap(){
      myLatLng = new google.maps.LatLng(<%= current_user.latlng[0] %>, <%= current_user.latlng[1] %>);
      map = new google.maps.Map(document.getElementById('map'),{
        center: myLatLng,
        zoom: 12
      });
      marker = new google.maps.Marker({
        map: map,
        position: myLatLng
     });
    }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['MAPS_API_KEY']%>&callback=initMap" async defer></script>
<% end %>
<% end %>

app/views/users/edit.html.slim
.row
  .application__sidebar.col-md-3
    == render 'users/info', user: current_user
    == render 'books/form', book: @book
    = render 'layouts/errors', obj: @user
= form_for(@user) do |f|
  .field
    = f.label :name
    = f.text_field :name, class: "name"
  .field
    = f.label :image
    = f.attachment_field :profile_image, class: "user_image"
  .field
    = f.label :introduction
    = f.text_area :introduction, class: "introduction"
  .actions
    = f.submit

app/views/users/followers.html.slim
.row
  .col-xs-3
    h2
      | User info
    = render 'info', user: current_user
    h2
      | New book
    = render 'books/form', book: @book
  .col-xs-9
    h2
      = current_user==@user?"自分":@user.name
      | のフォロワーリスト
    = render 'index', users: @user.followers

app/views/users/followings.html.slim
.row
  .col-xs-3
    h2
      | User info
    = render 'info', user: current_user
    h2
      | New book
    = render 'books/form', book: @book
  .col-xs-9
    h2
      = current_user==@user?"自分":@user.name
      | がフォローしているリスト
    = render 'index', users: @user.followings

app/views/users/index.html.slim
.row
  .application__sidebar.col-md-3
    == render 'users/info', user: current_user
    == render 'books/form', book: @book
  .users_index.offset-md-1.col-md-8
    == render 'users/index', users: @users

app/views/users/show.html.slim
.row
  .application__sidebar.col-md-3
    == render 'users/info', user: @user
    == render 'books/form', book: @book
  .users__show.offset-md-1.col-md-8
    == render 'books/index',books: @books