config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations'
  }

  resources :users, only: %i[show edit update index] do
    member do
      get 'followers'
      get 'followings'
    end
    resource :relationships, only: %i[create destroy]
    resource :rooms, only: %i[show] do
      resources :chats, only: %i[create]
    end
  end

  resources :books do
    resource :favorites, only: %i[create destroy]
    resources :book_comments, only: %i[create]
  end

  resources :book_comments, only: %i[destroy]
  resources :chats, only: %i[destroy]

  root 'home#top'
  get 'home/about'
  get 'search' => 'searchs#search', as: 'search'
  patch 'map_display' => 'users#map_display', as: 'map_display'
end

app/models/chat.rb
# frozen_string_literal: true

class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :user_id, presence: true
  validates :room_id, presence: true
  validates :text, length: { maximum: 144, minimum: 1 }
end

app/controllers/chats_controller.rb
# frozen_string_literal: true

class ChatsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:user_id])
    @room = Room.entering(current_user, @user)
    @chat = current_user.chats.new(chat_params)
    @chat.room_id = @room.id
    @chat = Chat.new if @chat.save
  end

  def destroy
    chat = Chat.find(params[:id])
    @room = chat.room
    @room.user_rooms.each do |ur|
      @user = ur.user unless ur.user == current_user
    end
    chat.destroy
    @chat = Chat.new
  end

  private

  def chat_params
    params.require(:chat).permit(:text)
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_index.html.slim
table.table.table-hover.table-inverse
  thead
    tr.row
      th.col-md-5 = "#{current_user.name}(You)"
      th.col-md-2
      th.col-md-5 = user.name
  tbody.chats__tbody
    - chats.each do |c|
      tr[class="row chat chats__record--#{c.id}"]
        - if c.user == current_user
          td.col-md-5 = c.text
          td.col-md-2 = link_to '削除', c, method: :delete, remote: true
          td.col-md-5
        - else
          td.col-md-5
          td.col-md-2
          td.col-md-5 = c.text
= form_with(model: chat, url: user_rooms_chats_path(user), method: :post, data: {local: false, remote: true}) do |f|
  = f.text_field :text, class: 'col-xs-5 chats__text'

app/views/chats/create.js.erb
$('.chats__table').html(
  "<%= j(render partial: 'chats/index', locals: {chats: @room.chats, chat: @chat, user: @user}) %>"
)
$('.chats__text').val('')

app/views/chats/destroy.js.erb
$('.chats__table').html(
  "<%= j(render partial: 'chats/index', locals: {chats: @room.chats, chat: @chat, user: @user}) %>"
)