config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations'
  }

  resources :users, only: %i[show edit update index] do
    member do
      get 'followers'
      get 'followings'
    end
    resource :relationships, only: %i[create destroy]
    resource :rooms, only: %i[show] do
      resources :chats, only: %i[create]
    end
  end

  resources :books do
    resource :favorites, only: %i[create destroy]
    resources :book_comments, only: %i[create]
  end

  resources :book_comments, only: %i[destroy]
  resources :chats, only: %i[destroy]

  root 'home#top'
  get 'home/about'
  get 'search' => 'searchs#search', as: 'search'
  patch 'map_display' => 'users#map_display', as: 'map_display'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  has_many :favorites, dependent: :delete_all
  has_many :book_comments, dependent: :delete_all

  def favorited_by?(user)
    Favorite.where(user_id: user.id, book_id: id).exists?
  end

  def self.search(content, method)
    case method
    when 'perfect'
      where(title: content)
    when 'forward'
      where('title LIKE ?', "#{content}%")
    when 'backward'
      where('title LIKE ?', "%#{content}")
    when 'partial'
      where('title LIKE ?', "%#{content}%")
    end
  end
end

app/models/book_comment.rb
# frozen_string_literal: true

class BookComment < ApplicationRecord
  belongs_to :book
  belongs_to :user
  validates :body, presence: true
end

app/models/chat.rb
# frozen_string_literal: true

class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :user_id, presence: true
  validates :room_id, presence: true
  validates :text, length: { maximum: 144, minimum: 1 }
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'

  validates :follower_id, presence: true
  validates :followee_id, presence: true
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  has_many :user_rooms, dependent: :delete_all
  has_many :chats, dependent: :delete_all

  def self.entering(current_user, another_user)
    another_user.user_rooms.each do |ur|
      next unless current_user.user_rooms.find_by(room_id: ur.room_id)

      return self.find(ur.room_id)
    end
    room = self.create
    UserRoom.create(room_id: room.id, user_id: current_user.id)
    UserRoom.create(room_id: room.id, user_id: another_user.id)
    return room
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  include JpPrefecture

  jp_prefecture :prefectures

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable

  attachment :profile_image, destroy: false

  has_many :books
  has_many :favorites
  has_many :book_comments
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followee_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, foreign_key: 'follower_id', dependent: :destroy
  has_many :followings, through: :relationships, source: :followee
  has_many :user_rooms, dependent: :delete_all
  has_many :chats, dependent: :delete_all

  validates :name, presence: true, length: { maximum: 10, minimum: 2 }
  validates :introduction, length: { maximum: 50 }
  validates :postal_code, presence: true
  validates :prefectures, presence: true
  validates :city, presence: true
  validates :street, presence: true

  # enum prefectures: {
  #   hokkaido: 1,
  #   aomori: 2, iwate: 3, miyagi: 4, akita: 5, yamagata: 6, fukushima: 7,
  #   ibaraki: 8, tochigi: 9, gunma: 10, saitama: 11,
  #   chiba: 12, tokyo: 13, kanagawa: 14,
  #   niigata: 15, toyama: 16, ishikawa: 17, fukui: 18,
  #   yamanashi: 19, nagano: 20, gifu: 21, shizuoka: 22,
  #   aichi: 23, mie: 24, shiga: 25, kyoto: 26,
  #   osaka: 27, hyogo: 28, nara: 29, wakayama: 30,
  #   tottori: 31, shimane: 32, okayama: 33, hiroshima: 34,
  #   yamaguchi: 35, tokushima: 36, kagawa: 37, ehime: 38,
  #   kochi: 39, fukuoka: 40, saga: 41, nagasaki: 42,
  #   kumamoto: 43, oita: 44, miyazaki: 45, kagoshima: 46,
  #   okinawa: 47
  # }

  def following?(another_user)
    followings.include?(another_user)
  end

  def follow(another_user)
    return if self == another_user

    relationships.find_or_create_by(followee_id: another_user.id)
  end

  def unfollow(another_user)
    return if self == another_user

    relationship = relationships.find_by(followee_id: another_user.id)
    relationship&.destroy
  end

  def self.search(content, method)
    case method
    when 'perfect'
      where(name: content)
    when 'forward'
      where('name LIKE ?', "#{content}%")
    when 'backward'
      where('name LIKE ?', "%#{content}")
    when 'partial'
      where('name LIKE ?', "%#{content}%")
    end
  end

  def latlng
    return unless is_display_map

    begin
      Geocoder.search(prefectures + city).first.coordinates
    rescue
      update(is_display_map: false)
    end
  end
end

app/models/user_room.rb
# frozen_string_literal: true

class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :user_id, presence: true
  validates :room_id, presence: true
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :authenticate_user!, only: %i[create edit update destroy index]

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    screen_user(@book)
  end

  def create
    @book = current_user.books.new(book_params)
    if @book.save
      redirect_to @book
    else
      @books = Book.all
      render 'index'
    end
  end

  def update
    @book = Book.find(params[:id])
    screen_user(@book)
    if @book.update(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    screen_user(@book)
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def screen_user(book)
    redirect_to books_path unless book.user == current_user
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def top; end

  def about; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/sing_ups_helper.rb
module SingUpsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.slim
- if obj.errors.any?
  .msgBox
    div
      - n = obj.errors.count
      - if n == 1
        |  1 error prohibited this from being saved: 
      - else
        = n
        |  errors prohibited this from being saved: 
    ul
      - obj.errors.full_messages.each do |msg|
        li
          = msg

app/views/layouts/_footer.html.slim
footer
  .container
    .row
      .offset-md-10
        p
          small CopyRight Infratop.inc

app/views/layouts/_header.html.slim
header.navbar.navbar-expand-lg.navbar-light.bg-dark
  .container
    nav.nav.navbar-nav.navbar-left
      span.navbar-brand.mb-0.h1 Bookers
    nav.collapse.navbar-collapse
      ul.nav.navbar-nav.ml-auto
        - if user_signed_in?
          li = link_to ' Home', current_user, class: 'nav-item nav-link home'
          li = link_to ' Users', users_path, class: 'nav-item nav-link users'
          li = link_to ' Books', books_path, class: 'nav-item nav-link books'
          li = link_to ' logout', destroy_user_session_path, method: :delete,class: 'nav-item nav-link logout', data: { 'turbolinks' => false }
        - else
          li = link_to ' Home', root_path, class: 'nav-item nav-link home', data: { 'turbolinks' => false }
          li = link_to ' About', home_about_path, class: 'nav-item nav-link about'
          li = link_to ' sign up', new_user_registration_path, class: 'nav-item nav-link sign_up', data: { 'turbolinks' => false }
          li = link_to ' login', new_user_session_path, class: 'nav-item nav-link sign_in', data: { 'turbolinks' => false }

app/views/layouts/_search_form.html.slim
- if user_signed_in?
  .search-form[style="margin-top: 70px; text-align: center;"]
    = form_tag(search_path, method: :get) do
      = text_field_tag 'search[content]'
      = select_tag 'search[model]', options_for_select({ "User" => "user", "Book" => "book" })
      = select_tag 'search[method]', options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" })
      = submit_tag '検索'

app/views/layouts/application.html.slim
doctype html
html
  head
    title Bookers
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    script[src="https://jpostal-1006.appspot.com/jquery.jpostal.js"]
  body
    == render 'layouts/header'
    // == render 'layouts/search_form'
    main
      .container
        .application__notice#notice
          = notice
        = yield
        == render 'users/map'
    == render 'layouts/footer'